#!/usr/bin/env python

import sys, os, shutil, ConfigParser

cfgpath = '/usr/share/thumbnailers/'

config = ConfigParser.ConfigParser({'Dirs':'/tmp/', 'Thumb':'privatethumbs.png'})
config.read(cfgpath+'private.thumbnailer')

pathdict = tuple(config.get('PrivateThumbs', 'Dirs').split(';'))
print pathdict
thumbpath = config.get('PrivateThumbs', 'Thumb')
if not "/" in thumbpath:
	thumbpath = cfgpath+thumbpath

if sys.argv[1].startswith(pathdict):
  shutil.copyfile(thumbpath, sys.argv[2])
  exit(0)
  
exit(1)
